version: '2'
services:
  jenkins:
    build: jenkins
    volumes:
      - ./jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock    
    ports:
      - "80:8080"
      - "5000:5000"
      - "50000:50000"
  ivy:
    build: ivy
    ports:
      - "8080:8080"
  ivy-test:
    build: ivy
    ports:
      - "8090:8080"
