pipeline {
  agent {
    docker {
      image 'maven:3.6.2'
      args '--network=build-environment_default'
    }
  }

  triggers {
    cron '@midnight'
  }

  stages {
    stage('packaging') {
      steps {
        dir ('quick-start-tutorial') {
      	  sh 'mvn clean install -B'
          archiveArtifacts 'target/*.iar'
        }
      }
    }

    /*
    stage('testing') {
      steps {
        dir ('quick-start-tutorial-test') {
      	  sh 'mvn clean test -B'
          junit 'target/surefire-reports/*.xml'
        }
      }
    }
    */

    stage ('preview') {
      steps {
        dir ('quick-start-tutorial') {
          echo 'http://localhost:8090/ivy'
          sh 'curl -X POST ' +
            "http://ivy-test:8080/ivy/api/system/apps/${env.BRANCH_NAME} " +
            '-u admin:admin ' +
            '-H \'X-Requested-By: curl\' ' +
            '-F fileToDeploy=@target/quick-start-tutorial-7.4.0-SNAPSHOT.iar'
        }

        script {
          if (env.BRANCH_NAME == 'master') {
            timeout(time: 2, unit: "HOURS") {
              input message: 'Deploy to production?', ok: 'Yes'
            }
          }
        }
      }
    }

    stage('deploy') {
      when {
        branch 'master'
      }
      steps {
        dir ('quick-start-tutorial') {
          sh 'curl -X POST ' +
            'http://ivy:8080/ivy/api/system/apps/my-demo-app ' +
            '-u admin:admin ' +
            '-H \'X-Requested-By: curl\' ' +
            '-F fileToDeploy=@target/quick-start-tutorial-7.4.0-SNAPSHOT.iar'
        }
      }
    }
  }
}
