pipeline {
  agent {
    docker {
      image 'maven:3.6.2'
      args '--network=build-environment_default'
    }
  }

  stages {
    stage('packaging') {
      steps {
        dir ('quick-start-tutorial') {
      	  sh 'mvn clean install -B'
          archiveArtifacts 'target/*.iar'
        }
      }
    }

    /*
    stage('testing') {
      steps {
        dir ('quick-start-tutorial-test') {
      	  sh 'mvn clean test -B'
          junit 'target/surefire-reports/*.xml'
        }
      }
    }
    */
    
    stage('deploy') {
      steps {
        dir ('quick-start-tutorial') {
          sh 'curl -X POST ' +
            'http://ivy:8080/ivy/api/system/apps/my-demo-app ' +
            '-u admin:admin ' +
            '-H \'X-Requested-By: curl\' ' +
            '-F fileToDeploy=@target/quick-start-tutorial-7.4.0-SNAPSHOT.iar'
        }
      }
    }
  }
}
