pipeline {
  agent {
    docker {
      image 'maven:3.6.2'
    }
  }

  triggers {
    cron '@midnight'
    pollSCM '@hourly'
  }

  stages {
    stage('packaging') {
      steps {
        dir ('quick-start-tutorial') {
      	  sh 'mvn clean install -B'
          archiveArtifacts 'target/*.iar'
        }
      }
    }

    stage('testing') {
      steps {
        dir ('quick-start-tutorial-test') {
      	  sh 'mvn clean test -B'
          junit 'target/test-reports/*.xml'
        }
      }
    }
  }
}
